from logic import *

print(CBEIGE+'\n-------------------------------------------'+CEND)
print(CBEIGE+'-------------MYSTERIOUS PEOPLE-------------\n'+CEND)
print('Está preparado? Temos 3 pessoas nesse jogo.')
print('Elas são: Marcela, Clebin e Rincon.')
print('Mais abaixo, você poderá pedir dicas sobre eles;')
print('E então, deduzir os desafios abaixo:')
print(CBEIGE+'\n-------------------------------------------'+CEND)
print(CBEIGE+'-------------DESAFIOS DO JOGO--------------\n'+CEND)
print('Você tem que descobrir (de cada pessoa):')
print(CBLUE+'1.'+CEND+' A profissão;')
print(CBLUE+'2.'+CEND+' O mês de nascimento;')
print(CBLUE+'3.'+CEND+' A comida favorita.')
print(CBEIGE+'\n-------------------------------------------'+CEND)
print(CBEIGE+'--------------REGRAS DO JOGO---------------\n'+CEND)
print(CBLUE+'>.'+CEND+' São 3 dicas por pessoa para deduzir quais as respostas corretas dos desafios.')
print(CBLUE+'>.'+CEND+' São 27 chances no total (3 para cada uma dos 3 desafios das 3 pessoas.)')
print(CBLUE+'>.'+CEND+' Elas decrescem na medida em que você erra. Use-as com sabedoria, pois:')
print(CBLUE+'>.'+CEND+' Para vencer, você deve acertar ao menos DOIS desafios das 3 pessoas.')
print(CBEIGE+'\n-------------------------------------------'+CEND)
print(CBEIGE+'----------------SIMBORA!!!!----------------\n'+CEND)

action()